-keep class io.github.colorisland.ColorIslandModule { *; }
-keep class io.github.libxposed.** { *; }
-dontwarn io.github.libxposed.**
-keep class io.github.colorisland.IslandConfig { *; }
-keep class io.github.colorisland.island.** { *; }
-keep class io.github.colorisland.hook.** { *; }
-keep class io.github.colorisland.data.** { *; }
-dontwarn org.jetbrains.compose.**
-dontwarn top.yukonga.miuix.kmp.**
-keep class top.yukonga.miuix.kmp.** { *; }
-dontwarn kotlinx.coroutines.**
-keepclassmembers class kotlinx.coroutines.** { volatile <fields>; }
-keepattributes *Annotation*, InnerClasses, Signature, Exceptions
-keep class org.json.** { *; }
